on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

name: CI

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable

      - uses: actions-rs/install@v0.1
        with:
          crate: cargo-tarpaulin
          version: latest
          use-tool-cache: true

      - name: 'Run `cargo-tarpaulin`'
        run: cargo tarpaulin --workspace --run-types Tests --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
